const fs = require('fs')
var read = require('readline-sync')
let point =0
date = read.question('Enter the date')
month = read.question('Enter the month')
year = read.question('Enter the year')
if(year>2012)
console.log('kid')
else if(year<2012 & year>1992)
console.log('youth')
else if(year<1992 & year>1962)
console.log('adult')
else if(year<1962)
console.log('older')